<a href="https://colab.research.google.com/github/denizgcs/WPF-2fa-iki-adimli-kimilk-dogrulama-/blob/master/Miuul_Proje_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Bu çalışma
Python Programming for Data Science
eğitimi projesidir
Kural Tabanlı Sınıflandırma ile
Potansiyel Müşteri Getirisi Hesaplama

In [1]:
import pandas as pd
df=pd.read_csv("persona.csv")
df.head()

   PRICE   SOURCE   SEX COUNTRY  AGE
0     39  android  male     bra   17
1     39  android  male     bra   17
2     49  android  male     bra   17
3     29  android  male     tur   17
4     49  android  male     tur   17

In [ ]:
df.nunique()

PRICE       6
SOURCE      2
SEX         2
COUNTRY     6
AGE        46
dtype: int64

In [ ]:
df["PRICE"].value_counts()

PRICE
29    1305
39    1260
49    1031
19     992
59     212
9      200
Name: count, dtype: int64

In [ ]:
df["COUNTRY"].value_counts()

COUNTRY
usa    2065
bra    1496
deu     455
tur     451
fra     303
can     230
Name: count, dtype: int64

In [ ]:
df.groupby("COUNTRY")["PRICE"].sum()

COUNTRY
bra    51354
can     7730
deu    15485
fra    10177
tur    15689
usa    70225
Name: PRICE, dtype: int64

In [ ]:
df["SOURCE"].value_counts()

SOURCE
android    2974
ios        2026
Name: count, dtype: int64

In [ ]:
df.groupby("COUNTRY")["PRICE"].mean()

COUNTRY
bra    34.327540
can    33.608696
deu    34.032967
fra    33.587459
tur    34.787140
usa    34.007264
Name: PRICE, dtype: float64

In [ ]:
df.groupby("SOURCE")["PRICE"].mean()

SOURCE
android    34.174849
ios        34.069102
Name: PRICE, dtype: float64

In [ ]:
df.groupby(["COUNTRY","SOURCE"])["PRICE"].mean()

COUNTRY  SOURCE
bra      android    34.387029
         ios        34.222222
can      android    33.330709
         ios        33.951456
deu      android    33.869888
         ios        34.268817
fra      android    34.312500
         ios        32.776224
tur      android    36.229437
         ios        33.272727
usa      android    33.760357
         ios        34.371703
Name: PRICE, dtype: float64

In [ ]:
df.groupby(["COUNTRY","SOURCE","AGE"])["PRICE"].mean().sort_values()

COUNTRY  SOURCE   AGE
deu      android  26      9.0
fra      android  18     19.0
bra      ios      47     19.0
tur      ios      47     19.0
can      android  27     19.0
                         ...
fra      ios      20     49.0
usa      ios      32     54.0
bra      android  46     59.0
usa      android  36     59.0
fra      android  24     59.0
Name: PRICE, Length: 248, dtype: float64

In [ ]:
df["AGE_CAT"] = pd.cut(df["AGE"],
                       bins=[0, 18, 23, 30, 40, 70],
                       labels=["0_18", "19_23", "24_30", "31_40", "41_70"])

In [ ]:
df["PRICE"].min()
df['PRICE'].max()

59

In [ ]:
df["SEGMENT"] = pd.cut(
    df["PRICE"],
    bins=[9, 21.5, 34, 46.5, 59],
    labels=["D", "C", "B", "A"],
    include_lowest=True
)

In [ ]:
df.head()

   PRICE   SOURCE   SEX COUNTRY  AGE AGE_CAT SEGMENT
0     39  android  male     bra   17    0_18       B
1     39  android  male     bra   17    0_18       B
2     49  android  male     bra   17    0_18       A
3     29  android  male     tur   17    0_18       C
4     49  android  male     tur   17    0_18       A

In [ ]:
print("source, country ve yas aragılına gore ortalama satıs fiyatı\n",df.groupby(["SOURCE","COUNTRY","AGE_CAT"])["PRICE"].sum())

source, country ve yas aragılına gore ortalama satıs fiyatı
 SOURCE   COUNTRY  AGE_CAT
android  bra      0_18        9789
                  19_23      11106
                  24_30       6147
                  31_40       4451
                  41_70       1381
         can      0_18        1522
                  19_23       1040
                  24_30        728
                  31_40          0
                  41_70        943
         deu      0_18        3038
                  19_23       2217
                  24_30       1475
                  31_40       1935
                  41_70        446
         fra      0_18        2186
                  19_23       2051
                  24_30        447
                  31_40        505
                  41_70        301
         tur      0_18        2911
                  19_23       1612
                  24_30       2668
                  31_40        517
                  41_70        661
         usa      0_18       15244
                  19_23      11673
                  24_30       7413
                  31_40       3930
                  41_70       3299
ios      bra      0_18        7437
                  19_23       3429
                  24_30       2758
                  31_40       2894
                  41_70       1962
         can      0_18        2160
                  19_23          0
                  24_30       1066
                  31_40        116
                  41_70        155
         deu      0_18        4064
                  19_23        340
                  24_30       1087
                  31_40        698
                  41_70        185
         fra      0_18        1949
                  19_23        681
                  24_30        677
                  31_40       1341
                  41_70         39
         tur      0_18        2466
                  19_23       2563
                  24_30       1109
                  31_40        436
                  41_70        746
         usa      0_18       11143
                  19_23       7276
                  24_30       5144
                  31_40       3083
                  41_70       2020
Name: PRICE, dtype: int64
source, country ve yas aragılına gore ortalama toplam asatıs miktarı
 SOURCE   COUNTRY  AGE_CAT
android  bra      0_18       281
                  19_23      324
                  24_30      183
                  31_40      129
                  41_70       39
         can      0_18        48
                  19_23       30
                  24_30       22
                  31_40        0
                  41_70       27
         deu      0_18        92
                  19_23       63
                  24_30       45
                  31_40       55
                  41_70       14
         fra      0_18        64
                  19_23       59
                  24_30       13
                  31_40       15
                  41_70        9
         tur      0_18        79
                  19_23       48
                  24_30       72
                  31_40       13
                  41_70       19
         usa      0_18       446
                  19_23      347
                  24_30      227
                  31_40      120
                  41_70       91
ios      bra      0_18       213
                  19_23      101
                  24_30       82
                  31_40       86
                  41_70       58
         can      0_18        60
                  19_23        0
                  24_30       34
                  31_40        4
                  41_70        5
         deu      0_18       116
                  19_23       10
                  24_30       33
                  31_40       22
                  41_70        5
         fra      0_18        61
                  19_23       19
                  24_30       23
                  31_40       39
                  41_70        1
         tur      0_18        74
                  19_23       77
                  24_30       31
                  31_40       14
                  41_70       24
         usa      0_18       327
                  19_23      204
                  24_30      146
                  31_40       97
                  41_70       60
dtype: int64

C:\Users\user\AppData\Local\Temp\ipykernel_9596\3713851974.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  print("source, country ve yas aragılına gore ortalama satıs fiyatı\n",df.groupby(["SOURCE","COUNTRY","AGE_CAT"])["PRICE"].sum())
C:\Users\user\AppData\Local\Temp\ipykernel_9596\3713851974.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  print("source, country ve yas aragılına gore ortalama toplam asatıs miktarı \n",df.groupby(["SOURCE","COUNTRY","AGE_CAT"]).size())

In [ ]:
print(" 33 yaşında ANDROID kullanan bir Türk kadını B segmentine aittir ortalama \n ",39.76923113,"\n getirisi olur \n")
print("35 yaşında IOS kullanan bir Fransız kadın C segmentine aittir ortalama \n",34.38,"\n getirisi olur \n")

 33 yaşında ANDROID kullanan bir Türk kadını B segmentine aittir ortalama
  39.76923113
 getirisi olur

35 yaşında IOS kullanan bir Fransız kadın C segmentine aittir ortalama
 34.38
 getirisi olur